### ISSUE TITLE
Help QAQ

### ISSUE THREAD

**Issue by Robertgao0818** [Cheukfung/Hackintosh-Intel-i7-8700K-Gigabyte-Z370-Aorus-Gaming5-Vega56#2]
不知道为啥，除了显卡不一样，就是装不上，哭了
自己加了DSDT，改了机型型号，感觉没啥问题，但是U盘安装就卡苹果标志

[config.zip](https://github.com/Cheukfung/Hackintosh-Intel-i7-8700K-Gigabyte-Z370-Aorus-Gaming5-Vega56/files/5560959/config.zip)

**Comment by Cheukfung** [comment]
@Robertgao0818 要确定两个
1.主板bios版本是不是F7 我试过f15版本是不行的。
2.主板是不是解锁了cfg 我的主板手动解锁了，如果你的没解锁，需要在Kernel -> Quirks下，打开 AppleCpuPmCfgLock 以及 AppleXcpmCfgLock

**Comment by Cheukfung** [comment]
@Robertgao0818 还有就是oc不需要加dsdt进去 官方教程明确说了的 你和我的配置如果是一样 bios版本一样 只,需要在Kernel -> Quirks下，打开AppleCpuPmCfgLock 以及 AppleXcpmCfgLock 应该就能正常使用，除了机箱前置的USB接口可能会不行（我做了USB定制）
