### ISSUE TITLE
报错OC:Failed to load configuration

### ISSUE THREAD

**Issue by justbegin01** [Cheukfung/Hackintosh-Intel-i7-8700K-Gigabyte-Z370-Aorus-Gaming5-Vega56#3]
大神，这个要怎么解决啊
8700k
技嘉z370 gaming 5
580 显卡
重新下载好几次了，都没有办法解决

**Comment by justbegin01** [comment]
大神，帮忙看看，谢谢

**Comment by Cheukfung** [comment]
> 大神，这个要怎么解决啊
> 8700k
> 技嘉z370 gaming 5
> 580 显卡
> 重新下载好几次了，都没有办法解决

这个是配置文件出错 你下载下来什么也没改吗

**Comment by justbegin01** [comment]
是的啊，我下载来什么也没改啊，直接放到引导盘

**Comment by justbegin01** [comment]
我跟你的配置除了显卡不一样，其他都一样啊。/

**Comment by Cheukfung** [comment]
> 我跟你的配置除了显卡不一样，其他都一样啊。/

我更新了一下配置文件，你重新下载试试

**Comment by 130185830** [comment]
我的也一样。oc:failed to load configuration 下了好几次都一样。

**Comment by Cheukfung** [comment]
> 是的啊，我下载来什么也没改啊，直接放到引导盘

转gitee更新了，你可以再试试https://gitee.com/cheukfungho/hackintosh-intel-i7-8700-k-gigabyte-z370-aorus-gaming5-vega56

**Comment by Cheukfung** [comment]
> 我的也一样。oc:failed to load configuration 下了好几次都一样。

转gitee更新了，你可以再试试https://gitee.com/cheukfungho/hackintosh-intel-i7-8700-k-gigabyte-z370-aorus-gaming5-vega56
